name: Release & Deploy
description: |
  `deploy`s the project and handles updating of the project version / tagging.
  Expects Maven to be setup to support `mvn deploy`, e.g. an appropriate JDK, repository configuration with credentials etc.

inputs:
  next-version:
    required: false
    description: 'Override next development version (e.g. if current version in master is 5.0-SNAPSHOT, the "next-version" should be 5.1-SNAPSHOT). If not set then the version will be calculated by maven release plugin'

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Convert to non-`SNAPSHOT`
      id: version
      shell: bash
      run: |
        source /dev/stdin <<< "$(curl --fail --retry 5 --retry-all-errors --show-error --silent https://raw.githubusercontent.com/hazelcast/mono-actions/main/.github/scripts/maven.functions.sh)"

        mvn \
          versions:set \
          $(get_maven_args) \
          -DgenerateBackupPoms=false \
          -DremoveSnapshot=true

        version=$(get_project_version)
        echo "version=${version}" >> ${GITHUB_OUTPUT}

        git commit --all --message "Release \`${version}\`"
        git push

    - name: Tag
      shell: bash
      id: tag
      run: |
        tag=v${{ steps.version.outputs.version }}
        echo "tag=${tag}" >> ${GITHUB_OUTPUT}

        git tag "${tag}"
        git push --atomic origin HEAD "refs/tags/${tag}"

    - name: Deploy
      shell: bash
      run: |
        source /dev/stdin <<< "$(curl --fail --retry 5 --retry-all-errors --show-error --silent https://raw.githubusercontent.com/hazelcast/mono-actions/main/.github/scripts/maven.functions.sh)"

        mvn \
          deploy \
          $(get_maven_args) \
          -DskipTests

    - name: Update to new version
      shell: bash
      run: |
        source /dev/stdin <<< "$(curl --fail --retry 5 --retry-all-errors --show-error --silent https://raw.githubusercontent.com/hazelcast/mono-actions/main/.github/scripts/maven.functions.sh)"

        if [[ -n "${NEXT_VERSION}" ]]; then
          version_args=(-DnewVersion="${NEXT_VERSION}")
        else
          version_args=(-DnextSnapshot=true)
        fi

        mvn versions:set \
          $(get_maven_args) \
          -DgenerateBackupPoms=false \
          "${version_args[@]}"

        git commit --all --message "Upgrade version to \`$(get_project_version)\`"
        git push
      env:
        NEXT_VERSION: ${{ inputs.next-version }}

    - uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
      with:
        fail_on_unmatched_files: true
        files: '**/target/*.jar'
        name: ${{ steps.version.outputs.version }}
        tag_name: ${{ steps.tag.outputs.tag }}
